/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Atividade;

public class App {
    public static void main(String[] args) {
      App aplicacao = new App();
      Pessoa jog= new Pessoa("name");
      Piloto per1= new Piloto ("name");
      Equipes grup= new Equipes("grupo");
      Mecanicos per2= new Mecanicos("name");
    }
}
