/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Atividade;

public class App {
    public static void main(String[] args) {
      App aplicacao = new App();
      Pessoa jog= new Pessoa("ff");
      Piloto per1= new Piloto ("g");
      Equipes grup= new Equipes("hh");
      Mecanicos per2= new Mecanicos("f");
    }
}
